### ISSUE TITLE
MetadataAttributes define minOccurs and maxOccurs twice

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#42]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/38

**Comment by jgager** [comment]
The min/max occurs on local representation will be prohibited. It is necessary to do this to account for container only attributes where local representation is not used

**Comment by glennmdt** [comment]
Noted. Closing ticket.

**Comment by dosse** [comment]
@sdmx3mdt What is meant with "will be prohibited" Is there still something to be done on this? In this case the ticket should not be closed.

Also, using oXygen, I auto-generated an metadata message instance from the metadata message schema, and it looks as follow:

               <metadata:Attribute id="id40">
                       <metadata:Value>Value12</metadata:Value>
                       <metadata:Value>Value13</metadata:Value>




                       <metadata:Attribute id="id43">
                              <metadata:Value>Value14</metadata:Value>
                              <metadata:Value>Value15</metadata:Value>




                       </metadata:Attribute>
                       <metadata:Attribute id="id46">


                              <common:Text xml:lang="en">Text16</common:Text>
                              <common:Text xml:lang="en">Text17</common:Text>


                       </metadata:Attribute>
               </metadata:Attribute>
               <metadata:Attribute id="id49">


                       <common:Text xml:lang="en">Text18</common:Text>
                       <common:Text xml:lang="en">Text19</common:Text>


                       <metadata:Attribute id="id52">




                              <common:StructuredText xml:lang="en">
                              </common:StructuredText>
                              <common:StructuredText xml:lang="en">
                              </common:StructuredText>
                       </metadata:Attribute>
                       <metadata:Attribute id="id55">




                              <common:StructuredText xml:lang="en">
                              </common:StructuredText>
                              <common:StructuredText xml:lang="en">
                              </common:StructuredText>
                       </metadata:Attribute>
               </metadata:Attribute>
You see that maxOccurs is currently not "prohibited" in the XML metadata message. Could you please clarify?

Note: there is a different approach for modelling Text and StructuredText between measures/attributes in XML data messages and ref metadata in XML metadata messages. Could this be done in a coherent way? It feels like the measures/attributes in XML data messages are the better approach. This is currently be looked at by TF2.

**Comment by jgager** [comment]
The changes has not been pushed in, and you are correct that this should not be closed yet. I was simply noting my planned approach to solving this since I thought it warranted some discussion.

The example above is the actual metadata message, not the metadata structure, and therefore not applicable to this particular ticket. That being said, I do take your point about the differences between the data and metadata messages. I agree that we could look at harmonizing them, but first let me explain why we are not simply reusing the common:ValueType that is used in the data messages for the metadata messages:

The main reason is that the data messages are structure specific, and we rely on the structure specific generation rules to refine the common:ValueType to only allow the text content, the Text element, or the StructuredText element. Without this refinement, the ValueType allows for mixing of all these. So something like:

```
<Value>blah blah<Text xml:lang="en">foo</Text><StructuredText xml:lang="en"><xhtml:em>bar</xhtml:em></StructuredText>blah blah</Value>
```
is valid. And since the metadata messages are generic (there is no such structure specific refinement happening), it would always be allowed. By modeling this as a choice, we can restrict that only one be used. If we did want to harmonize, it would probably mean adopting the metadata approach for the data messages (e.g. having a Value element instead of the mixed text). We could probably accomplish this by creating an AnnotableValueType that extends AnnotableType with this choice model. Then the CompType in the data messages and AttributeType in the metadata messages can be derived from this.

**Comment by glennmdt** [comment]
@jgager is there anything left to do on this issue or can the tickets be closed?

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request.
Ticket will be reopened if pull request rejected.
