### ISSUE TITLE
Change the collections of structures in the Structure Message

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#77]
A change to the organisation and naming of collections in the Structure Message was approved by SDMX TWG at the 27 July 2021 meeting.

* Flatten and rename the collections
* Order the collections alphabetically in the schema
* Allow the collections to appear in any order in the structure message

Details in the attached document:
[SDMX TWG TF2 - public review issue #7 - Structure collection naming convention.docx](https://github.com/glennmdt/sdmx-ml/files/6894020/SDMX.TWG.TF2.-.public.review.issue.7.-.Structure.collection.naming.convention.docx)

Public Consultation ticket reference: 
https://github.com/sdmx3mdt/public-consultation/issues/7

**Comment by jgager** [comment]
@glennmdt I did not see where the alphabetizing was included in the attached document and in my opinion that would not provide any value. Since the elements are now in an xs:any container, the order does not matter in the instances. And in terms of understanding the schemas, I think the logical grouping we have make more sense.

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request. 
Ticket will be reopened if pull request rejected.

**Comment by glennmdt** [comment]
Can the structures be ordered alphabetically? 
Apparently that was agreed, if not made explicit in the document :-)

**Comment by glennmdt** [comment]
Pushed to feature branch Commit 13
https://github.com/sdmx3mdt/sdmx-ml/commit/3dcfb8fc3b398e994ccb9f1779d828a7dced01b7
