### ISSUE TITLE
Add non-localised "Value" and localised "URL"s to "Annotation" object

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#78]
Changes to the annotations model to add non-localised "Value" and localised "URL"s.

Details in the attached document:
[SDMX TWG TF2 - public review issue #34 - Enhancing SDMX artefact annotations.docx](https://github.com/glennmdt/sdmx-ml/files/6894173/SDMX.TWG.TF2.-.public.review.issue.34.-.Enhancing.SDMX.artefact.annotations.docx)

Public Consultation ticket reference:
https://github.com/sdmx3mdt/public-consultation/issues/34

**Comment by jgager** [comment]
@glennmdt I am not sure I agree with the suggested implementation here. I think we should simply add an optional language to AnnotationURL and make it repeatable. We can then document that if a language does not exist, the resource is not localised.

The value suggestion is fine (outside of my general object to people trying to jam functionality into annotations).

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request. 
Ticket will be reopened if pull request rejected.

**Comment by dosse** [comment]
@jgager I agreed with your proposed elegant way of implementing localisable URLs.

I'm wondering about your fear of "_people trying to jam functionality into annotations_". In how far are you questioning the approaches proposed in the SDMX [“Guidelines on the use of the SDMX Annotations”](https://sdmx.org/wp-content/uploads/Guidelines-on-the-use-of-SDMX-Annotations.pdf), e.g. the need to express in SDMX that a code is to be selected by DEFAULT in a dataflow presentation (independently from the current locale)? What better solutions would you have in mind, which would avoid the usage of annotations for presentational or other purposes? I'm really much interested in your view about that because our developers also complain about the overuse of the technically rather inefficient annotations.

**Comment by jgager** [comment]
@dosse I have always felt that the extensibility of XML is vastly under utilized. If there is specific functionality that is needed, I feel it should be explicitly modeled and documented in standard way that can be easily understood by the tools already being used. The problem with parsing annotations, is that a lot of the time it is going to come down to parsing text values that may or may not conform to what is intended based on the annotation type. It would be much better for implementers in these scenarios to define schemas to explicitly support what is needed. These schemas can be published and those that want to utilize them can do so with more confidence that the information they are processing will conform to the agreed upon model.

Now, in terms of how this is accomplished, there are different options to consider. For example, if I only need to add an attribute that has some additional meaning, I could simply extend the type(s) that need this attribute to include it. Then, at the instance level, you can use the xsi:type to allow the new attribute to be added. So long as the schemas are published, and processor would be able to retrieve and validate that the instance is still valid. And if the system processing does not understand or need the additional attribute, there is no harm in it being ignored (remember, from the standard point of view, all extensions are optional).

Another example that would be worth considering is to have a sibling element similar to Annotations (in that it optionally exists on most artifacts) that can serve as the base for extended functionality. This could be modeled in the schemas as a single element with xs:any content (strict or lax) or a repeated element with an abstract or no type, so that one has to be declared at the instance level. The decision would really come down to what information you wanted on the extensions. For example, let's suppose you want a bit of metadata describing the extension and its purpose (because maybe you feel the schema is not enough). I could define an abstract type that has the following attributes required:

- publisher
- type (some agreed, possibly extensible controlled vocabulary)
- url

Any type would then have be derived from this and would specify this information.

As an example, let's suppose we went with the latter approach and called the element "Extension". You might have something like this:

```
<Code urn="..." value="A">
   ...
   <Extension publisher="SDMX" type="CODE_COMPOSITION" url="..." xsi:type="sdmx-x:CodeComposition">
      <sdmx-x:Code value="A1"/>
      <sdmx-x:Operator value="+"/>
      <sdmx-x:Code value="A2"/>
   </Extension>
</Code>
```
And as you can imagine, I could have other Extension elements for other purposes.

My fundamental point is that XML is already extensible, and that functionality should be utilized. I of course understand that there are other exchange formats to consider. I personally have worked with and have done similar things in JSON, but admittedly never dove too deep into JSON schema (I found the tools around at the time very lacking and haven't had the need to revisit).

**Comment by dosse** [comment]
@jgager Thanks a lot for these detailed ideas. I will discuss this with our devs and initiate a topic at the SDMX-TWG as required.
