### ISSUE TITLE
Use '*' as the version in URNs for versionless artefacts

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#89]
Relating to public consultation issue https://github.com/sdmx3mdt/public-consultation/issues/24

Decision from the 02 Sept 2021 release candidate approval meeting:
For versionless artefacts like Organisation Schemes, use a * in the version part of the URN rather than 1.0 or not specifying a version.

**Comment by jgager** [comment]
@glennmdt this is going to take some time to implement if we want to restrict the urn and reference types based on the maintainables that are versionless, and I will need a full list of these versionless artefacts (including the items) in order to properly do so.

**Comment by glennmdt** [comment]
@jgager I've asked Stratos in particular if there is a definitive list of versionless artefacts.

**Comment by dosse** [comment]
@jgager The always versionless artefacts are those that were fixed to "1.0" in SDMX 2.1. It concerns all artefacts derived from the OrganisationsSchemeType. Those are:
- AgencyScheme
- DataConsumerScheme
- DataProviderScheme
- MetadataProviderScheme
- OrganisationUnitScheme

"*" creates confusion because in REST it means "all versions" rather than no version. SDMX-JSON implements this as prescribed in the agreed semantic versioning feature and as stated in the [major changes document](https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/ETl7LBYhBVtErDJO19SzKYYBFk2KCB_fWhCKDsg5FdtPSA?e=CTQ5f5): “_organisations may continue to use the pre-existing two-digit versioning strategy, or not to version artefacts **by omitting the version property**. The version number no longer defaults to 1.0 if not explicitly set._” through the possibility to omit the version part "(x.y.z)" in URNs, e.g. this is allowed:
- urn:sdmx.org.sdmx.infomodel.base.DataProviderScheme=SDMX:DATA_PROVIDERS
- urn:sdmx.org.sdmx.infomodel.datastructure.Dataflow=OECD:DATAFLOW_ID
- urn:sdmx.org.sdmx.infomodel.codelist.Code=OECD:CODELIST_ID.CODE_ID 

How complicated would it be on your end to do the same in SDMX-ML?

**Comment by jgager** [comment]
It will take some effort because the regex patterns are relying on the presence of the parentheses for the version part of the urn. What this allowed me to do is make the patterns very explicit. For example a code list urn doesn’t allow for the component part (it terminates after the parentheses). Basically, we assume every urn is going to have a version part. 

It should be possible to come up with the correct derivations given the lack of the version part, but it will just take some time- and I won’t be free to work on this until at least Friday, and possibly not until Sunday. 

Implementation would be simplified by keeping the version part and using empty parentheses or another character to indicate no versioning (e.g. (-)). But I certainly understand that such a change would have impacts elsewhere.

**Comment by dosse** [comment]
@jgager In JSON this was achieved rather easily by using a specific pattern for the URN of each artefact type without pattern inheritance or review. The version part is then just optional. Indeed, there is some repetition, but at least it's very simple and straightforward. Since the goal is to clearly indicate no version, I guess it's still ok (even if less elegant) to use empty parentheses.

**Comment by dosse** [comment]
@jgager I made a pull request with the required changes to use empty parentheses "**()**" instead of "**(*)**" for non-versioned artefacts, including for OrganisationScheme types. Note that ordinary (non-wildcarded) URNs of artefacts can also be non-versioned. I have added this. This should validate, unless I missed something, that this ticket should be easily solvable.

**Comment by glennmdt** [comment]
Change cancelled following TWG agreement to retain the pre-existing (1.0) for describing versionless artefacts in URNs.
