### ISSUE TITLE
Attribute attachment - change the name of the 'none' option to 'dataflow'

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#90]
Relating to public consultation issue https://github.com/sdmx3mdt/public-consultation/issues/15

Decision from the 02 Sept 2021 release candidate approval meeting:
Concerning attribute attachment in the DSD - change the name of the 'None' option to 'Dataflow' (reason: to clarify what this attachment level means).
![image](https://user-images.githubusercontent.com/26928385/131882847-703cc571-089b-4073-9b48-90ffd71faca7.png)

The description of the element in the schema should also be updated to state:
_"The attribute will always be treated as a dataflow level attribute."_

**Comment by dosse** [comment]
@jgager I would propose to reword the description to:  
"This means that the value of the attribute varies per dataflow. It is the data modeller's responsibility to design or use non-overlapping dataflows that do not have observations in common, otherwise the integrity of dataflow-specific attribute values is not assured by the model, e.g. when querying those data through its DSD."

**Comment by glennmdt** [comment]
Closed - included in sdmx3mdt repo commit 14
